
const TEXT_BUNDLES = {
    'pt-BR': {
        'intro.byline': 'por {author}',
        'intro.startAdventure': 'Iniciar aventura',
        'tabs.game': 'Jogo',
        'tabs.editor': 'Editor',
        'sections.tiles': 'Tiles',
        'sections.world': 'Mundo',
        'sections.objects': 'Objetos',
        'sections.npcs': 'NPCs',
        'sections.enemies': 'Inimigos',
        'sections.project': 'Projeto',
        'buttons.reset': 'Reiniciar',
        'buttons.newGame': 'Novo jogo',
        'buttons.remove': 'Remover',
        'buttons.move': 'Mover',
        'aria.reset': 'Reiniciar a partida atual',
        'aria.newGame': 'Criar um novo jogo do zero em outra aba',
        'touchControls.show': 'Exibir controles',
        'touchControls.hide': 'Ocultar controles',
        'touchControls.upLabel': 'Mover para cima',
        'touchControls.downLabel': 'Mover para baixo',
        'touchControls.leftLabel': 'Mover para a esquerda',
        'touchControls.rightLabel': 'Mover para a direita',
        'doors.variableLocked': 'Não abre com chave.',
        'doors.openedRemaining': 'Você usou uma chave para abrir a porta. Restam: {value}.',
        'doors.opened': 'Você usou uma chave para abrir a porta.',
        'doors.locked': 'Porta trancada. Precisa de uma chave.',
        'doors.unlockedSkill': 'Sua habilidade abriu a porta sem usar chave.',
        'log.engineReady': 'Tiny RPG Studio engine initialized successfully.',
        'npc.dialog.defaultLabel': 'Diálogo padrão:',
        'npc.dialog.placeholder': 'Digite o diálogo do NPC...',
        'npc.reward.defaultLabel': 'Ativar variável:',
        'npc.toggle.create': 'Criar diálogo alternativo',
        'npc.toggle.hide': 'Ocultar diálogo alternativo',
        'npc.conditional.variableLabel': 'Condição (variável):',
        'npc.conditional.textLabel': 'Texto alternativo:',
        'npc.conditional.placeholder': 'Mensagem exibida quando a variável estiver ON.',
        'npc.conditional.rewardLabel': 'Ativar variável (condicional):',
        'npc.delete': 'Remover NPC',
        'npc.defaultName': 'NPC',
        'npc.variant.label': 'Aparência dos NPCs',
        'npc.variant.human': 'Humano',
        'npc.variant.elf': 'Elfo',
        'npc.variant.dwarf': 'Anão',
        'npc.variant.fixed': 'Extras',
        'npcs.names.oldMage': 'Velho Mago',
        'npcs.names.oldMage.human': 'Velho Mago',
        'npcs.names.oldMage.elf': 'Velho Mago',
        'npcs.names.oldMage.dwarf': 'Velho Mago',
        'npcs.names.villagerMan': 'Homem comum',
        'npcs.names.villagerMan.human': 'Homem comum',
        'npcs.names.villagerMan.elf': 'Homem comum',
        'npcs.names.villagerMan.dwarf': 'Homem comum',
        'npcs.names.villagerWoman': 'Mulher comum',
        'npcs.names.villagerWoman.human': 'Mulher comum',
        'npcs.names.villagerWoman.elf': 'Mulher comum',
        'npcs.names.villagerWoman.dwarf': 'Mulher comum',
        'npcs.names.child': 'Criança curiosa',
        'npcs.names.child.human': 'Criança curiosa',
        'npcs.names.child.elf': 'Criança curiosa',
        'npcs.names.child.dwarf': 'Criança curiosa',
        'npcs.names.thoughtBubble': 'Balão',
        'npcs.names.woodenSign': 'Placa de madeira',
        'npcs.names.king': 'Rei',
        'npcs.names.king.human': 'Rei',
        'npcs.names.king.elf': 'Rei',
        'npcs.names.king.dwarf': 'Rei',
        'npcs.names.knight': 'Cavaleiro',
        'npcs.names.knight.human': 'Cavaleiro',
        'npcs.names.knight.elf': 'Cavaleiro',
        'npcs.names.knight.dwarf': 'Cavaleiro',
        'npcs.names.thief': 'Ladra',
        'npcs.names.thief.human': 'Ladra',
        'npcs.names.thief.elf': 'Ladra',
        'npcs.names.thief.dwarf': 'Ladra',
        'npcs.names.blacksmith': 'Ferreira',
        'npcs.names.blacksmith.human': 'Ferreira',
        'npcs.names.blacksmith.elf': 'Ferreira',
        'npcs.names.blacksmith.dwarf': 'Ferreira',
        'npcs.dialog.oldMage': 'Eu guardo segredos antigos.',
        'npcs.dialog.oldMage.human': 'Eu guardo segredos antigos.',
        'npcs.dialog.oldMage.elf': 'As árvores contam histórias para quem escuta.',
        'npcs.dialog.oldMage.dwarf': 'Lendas ecoam nas cavernas profundas.',
        'npcs.dialog.villagerMan': 'Bom dia! Posso ajudar?',
        'npcs.dialog.villagerMan.human': 'Bom dia! Posso ajudar?',
        'npcs.dialog.villagerMan.elf': 'Que a floresta guie seus passos.',
        'npcs.dialog.villagerMan.dwarf': 'Minhas mãos conhecem martelo e picareta.',
        'npcs.dialog.villagerWoman': 'Que dia lindo para explorar.',
        'npcs.dialog.villagerWoman.human': 'Que dia lindo para explorar.',
        'npcs.dialog.villagerWoman.elf': 'As flores florescem com boas intenções.',
        'npcs.dialog.villagerWoman.dwarf': 'O som das forjas acalma o coração.',
        'npcs.dialog.child': 'Vamos brincar de aventura!',
        'npcs.dialog.child.human': 'Vamos brincar de aventura!',
        'npcs.dialog.child.elf': 'Quer correr pelos bosques comigo?',
        'npcs.dialog.child.dwarf': 'Vamos cavar um túnel secreto!',
        'npcs.dialog.thoughtBubble': ' ... ',
        'npcs.dialog.woodenSign': 'Atenção aos perigos à frente.',
        'npcs.dialog.king': 'Proteja nosso reino!',
        'npcs.dialog.king.human': 'Proteja nosso reino!',
        'npcs.dialog.king.elf': 'Honre a natureza acima de tudo.',
        'npcs.dialog.king.dwarf': 'Defenda as minas com honra e aço.',
        'npcs.dialog.knight': 'Estou pronto para lutar.',
        'npcs.dialog.knight.human': 'Estou pronto para lutar.',
        'npcs.dialog.knight.elf': 'Luto para manter o verde vivo.',
        'npcs.dialog.knight.dwarf': 'Minha armadura ressoa como um tambor de guerra.',
        'npcs.dialog.thief': 'Ninguém me pega no ato.',
        'npcs.dialog.thief.human': 'Ninguém me pega no ato.',
        'npcs.dialog.thief.elf': 'Sou sombra entre galhos e folhas.',
        'npcs.dialog.thief.dwarf': 'Entre pedras e ouro, ninguém me vê chegar.',
        'npcs.dialog.blacksmith': 'Minhas forjas estão em brasas.',
        'npcs.dialog.blacksmith.human': 'Minhas forjas estão em brasas.',
        'npcs.dialog.blacksmith.elf': 'Forjo com madeira viva e aço leve.',
        'npcs.dialog.blacksmith.dwarf': 'Aço e pedra; é assim que se constrói.',
        'npc.status.available': 'Disponível',
        'npc.status.position': 'Mapa ({col}, {row}) - ({x}, {y})',
        'project.group.development': 'Desenvolvimento',
        'project.group.testing': 'Testes',
        'project.group.appearance': 'Visual',
        'project.group.online': 'Online',
        'project.online.warning': 'O modo online ainda está em desenvolvimento. Ele não está completo e pode conter bugs.',
        'project.online.enabled': 'Modo Online',
        'project.online.p2Spawn': 'P2 inicia em:',
        'project.online.spawnUnset': 'não definido',
        'project.online.generateLink': 'Gerar Link Online',
        'buttons.server': 'Server',
        'server.modal.title': 'Status do Servidor',
        'server.modal.status': 'Status',
        'server.modal.ping': 'Ping',
        'server.modal.players': 'Jogadores',
        'server.modal.room': 'Sala',
        'server.modal.role': 'Papel',
        'server.modal.disconnected': 'Desconectado',
        'server.modal.connected': 'Conectado',
        'server.modal.connecting': 'Conectando...',
        'server.modal.host': 'Host',
        'server.modal.guest': 'Guest',
        'server.modal.spectator': 'Espectador',
        'server.modal.noSession': 'Sem sessão ativa',
        'server.modal.close': 'Fechar',
        'server.modal.kick': 'Expulsar',
        'server.full.title': 'Servidor lotado',
        'server.full.message': 'Esta sala já tem 2 jogadores. Tente outra sala.',
        'server.kicked.title': 'Você foi expulso',
        'server.kicked.message': 'O host removeu você da sala.',
        'server.kicked.button': 'Voltar ao início',
        'project.hideHud': 'Esconder HUD',
        'project.disablePixelFont': 'Desativar fonte pixel art',
        'project.showVariableLinks': 'Mostrar ligações de variáveis no editor',
        'project.disableSkills': 'Desativar skills',
        'project.group.info': 'Informações',
        'project.group.export': 'Compartilhar',
        'project.titleLabel': 'Nome do jogo',
        'project.titlePlaceholder': 'Ex.: Lendas do Vale',
        'project.authorLabel': 'Autor',
        'project.authorPlaceholder': 'Seu nome ou estúdio',
        'project.languageLabel': 'Idioma',
        'project.generateUrl': 'Gerar URL do jogo',
        'project.shareUrlLabel': 'URL do jogo',
        'project.importHTML': 'Importar Projeto',
        'project.generateHTML': 'Exportar Projeto',
        'pixelArtEditor.title': 'Editor de Pixel Art',
        'pixelArtEditor.closeAria': 'Fechar editor de pixel art',
        'pixelArtEditor.paint': 'Pintar',
        'pixelArtEditor.erase': 'Apagar',
        'pixelArtEditor.reset': 'Restaurar padrão',
        'pixelArtEditor.save': 'Salvar',
        'pixelArtEditor.copyCode': 'Copiar código',
        'pixelArtEditor.copyCodeDone': 'Copiado!',
        'pixelArtEditor.frameLabel': 'Frame {index}',
        'pixelArtEditor.paletteColor': 'Cor {index}',
        'pixelArtEditor.paletteTransparent': 'Transparente',
        'project.variables.title': 'Variáveis do jogo',
        'project.variables.usage': '{used}/{total} usadas',
        'project.variables.used': 'Em uso',
        'project.variables.unused': 'Sem uso',
        'project.variables.toggle.show': 'Mostrar variáveis',
        'project.variables.toggle.hide': 'Esconder variáveis',
        'project.skills.title': 'Skills do jogo',
        'project.skills.toggle.show': 'Mostrar skills',
        'project.skills.toggle.hide': 'Esconder skills',
        'project.skills.resetOrder': 'Restaurar ordem padrão',
        'project.skills.disabled': 'Sistema de skills desativado',
        'project.skills.level': 'Nível {value}',
        'project.test.title': 'Ajuda nos testes',
        'project.test.toggle.show': 'Mostrar',
        'project.test.toggle.hide': 'Esconder',
        'project.test.hint': 'Apenas para testar: essas opções não entram na URL gerada.',
        'project.test.startLevel': 'Inicia com nível',
        'project.test.levelOption': 'Nível {value}',
        'project.test.skills': 'Ativar skills no teste',
        'project.test.skillsDisabled': 'Skills desativadas para este jogo.',
        'project.test.godMode': 'God mode (imortal)',
        'project.test.debugVision': 'Debug: Visão do inimigo',
        'project.shareHint': 'Gere uma URL e compartilhe com seus amigos!',
        'project.paletteDescription': 'Clique em uma cor para customizar',
        'project.palettePreset': 'Paleta predefinida',
        'project.palettePresetCustom': 'Personalizada',
        'project.paletteReset': 'Resetar Padrão',
        'project.colorPickerTitle': 'Escolher Cor',
        'project.colorCurrent': 'Atual',
        'project.colorNew': 'Nova',
        'project.colorCancel': 'Cancelar',
        'project.colorConfirm': 'Confirmar',
        'language.option.ptBR': 'Português (Brasil)',
        'language.option.enUS': 'English (US)',
        'history.undo': 'Desfazer',
        'history.redo': 'Refazer',
        'alerts.npc.full': 'Todos os NPCs já estão no mapa.',
        'alerts.npc.createError': 'Não foi possível criar o NPC.',
        'alerts.npc.selectFirst': 'Selecione um NPC para colocar.',
        'alerts.npc.placeError': 'Não foi possível posicionar o NPC.',
        'alerts.share.unavailable': 'Função de compartilhar não está disponível.',
        'alerts.share.copied': 'URL do jogo copiada para a área de transferência!',
        'alerts.share.copyPrompt': 'Copie a URL do seu jogo:',
        'alerts.share.generateError': 'Não foi possível gerar a URL do jogo.',
        'alerts.share.loadError': 'Não foi possível carregar o arquivo.',
        'enemies.damageInfo': ' - Dano: {value}',
        'enemies.variableLabel': 'Variável:',
        'enemies.xpBarLabel': 'Inimigos colocados',
        'enemies.xpBarValue': '{current} / {total} inimigos',
        'enemies.limitReached': 'Máximo de inimigos atingido',
        'enemies.names.giantRat': 'Rato Gigante',
        'enemies.names.bandit': 'Bandido',
        'enemies.names.darkKnight': 'Cavaleiro Negro',
        'enemies.names.necromancer': 'Necro',
        'enemies.names.dragon': 'Dragão',
        'enemies.names.skeleton': 'Esqueleto',
        'enemies.names.fallenKing': 'Rei Caído',
        'enemies.names.ancientDemon': 'Demônio Ancião',
        'enemies.defeat.dragon': 'Selo do Dragão ativado!',
        'enemies.defeat.fallenKing': 'Selo Real despertou!',
        'enemies.defeat.ancientDemon': 'Selo Demoníaco ativo!',
        'variables.none': 'Nenhuma',
        'variables.skill.bard': 'Habilidade: Bardo (falas extras)',
        'objects.info.available': 'Disponível (1 por cenário)',
        'objects.info.placed': 'Já no mapa (1 por cenário)',
        'objects.info.available.global': 'Disponível (1 por mundo)',
        'objects.info.placed.global': 'Já no mapa (1 por mundo)',
        'objects.info.count': 'No mapa: {count}/{max} no cenário',
        'objects.category.all': 'Todos',
        'objects.category.markers': 'Marcadores',
        'objects.category.equipment': 'Equipamentos',
        'objects.category.consumables': 'Consumíveis',
        'objects.category.obstacles': 'Obstáculos',
        'objects.category.triggers': 'Gatilhos',
        'objects.category.logic': 'Lógica',
        'variables.names.var1': 'Preto',
        'variables.names.var2': 'Azul Escuro',
        'variables.names.var3': 'Roxo',
        'variables.names.var4': 'Verde',
        'variables.names.var5': 'Marrom',
        'variables.names.var6': 'Cinza',
        'variables.names.var7': 'Azul Claro',
        'variables.names.var8': 'Rosa Choque',
        'variables.names.var9': 'Amarelo',
        'variables.names.var10': 'Cinza Claro',
        'variables.names.var11': 'Branco',
        'variables.names.var12': 'Vermelho',
        'variables.names.var13': 'Laranja',
        'variables.names.var14': 'Verde Claro',
        'variables.names.var15': 'Índigo',
        'variables.names.var16': 'Pêssego',
        'objects.switch.variableLabel': 'Variável associada:',
        'objects.switch.stateLabel': 'Estado atual: {state}',
        'objects.state.on': 'ON',
        'objects.state.off': 'OFF',
        'objects.status.doorOpened': 'Porta aberta',
        'objects.status.keyCollected': 'Chave coletada',
        'objects.status.potionCollected': 'Poção coletada',
        'objects.status.scrollUsed': 'Pergaminho usado',
        'objects.status.swordBroken': 'Espada quebrada',
        'objects.status.gameEnd': 'Final do jogo',
        'objects.end.textLabel': 'Mensagem final:',
        'objects.end.placeholder': 'Escreva a mensagem exibida antes de "The End"...',
        'objects.end.hint': 'Máx. {max} caracteres.',
        'objects.status.startMarker': 'Marcador inicial',
        'objects.label.door': 'Porta',
        'objects.label.doorVariable': 'Porta mágica',
        'objects.label.playerStart': 'Início do Jogador',
        'objects.label.playerStart1': 'Início do Jogador 1',
        'objects.label.playerStart2': 'Início do Jogador 2',
        'objects.label.playerEnd': 'Fim do Jogo',
        'objects.label.switch': 'Alavanca',
        'objects.label.key': 'Chave',
        'objects.label.lifePotion': 'Poção de Vida',
        'objects.label.sword': 'Espada de Aço',
        'objects.label.swordBronze': 'Espada de Bronze',
        'objects.label.swordWood': 'Espada de Madeira',
        'objects.label.xpScroll': 'Pergaminho de XP',
        'objects.label.logicGateNot': 'Porta NOT',
        'objects.label.logicGateAnd': 'Porta AND',
        'objects.label.logicGateOr': 'Porta OR',
        'objects.label.logicGateNand': 'Porta NAND',
        'objects.label.logicGateNor': 'Porta NOR',
        'objects.label.logicLed': 'LED',
        'objects.label.armor': 'Armadura',
        'objects.label.boots': 'Botas',
        'objects.label.trap': 'Armadilha',
        'objects.label.pressurePlate': 'Placa de Pressão',
        'objects.label.pushBox': 'Caixa',
        'objects.label.chest': 'Baú',
        'objects.desc.playerStart': 'Define o ponto de entrada do jogador na cena.',
        'objects.desc.playerEnd': 'Ao ser tocado, exibe uma mensagem e encerra o jogo.',
        'objects.desc.switch': 'O jogador interage para ligar ou desligar uma variável.',
        'objects.desc.door': 'Bloqueia a passagem; só abre se o jogador tiver uma chave.',
        'objects.desc.doorVariable': 'Abre ou fecha automaticamente conforme o estado de uma variável.',
        'objects.desc.key': 'Item coletável que abre uma Porta trancada.',
        'objects.desc.lifePotion': 'Item coletável que restaura pontos de vida quando usado.',
        'objects.desc.xpScroll': 'Item coletável que concede experiência ao ser lido.',
        'objects.desc.sword': 'Espada de aço coletável que bloqueia dano de ataques inimigos.',
        'objects.desc.swordBronze': 'Espada de bronze coletável que bloqueia dano de ataques inimigos.',
        'objects.desc.swordWood': 'Espada de madeira coletável que bloqueia dano de ataques inimigos.',
        'objects.desc.armor': 'Armadura coletável que reduz permanentemente o dano recebido.',
        'objects.desc.boots': 'Botas coletáveis que aumentam a velocidade de movimento do jogador.',
        'objects.desc.trap': 'Causa dano quando o jogador passa por cima, ativada por variável.',
        'objects.desc.pressurePlate': 'Ativa uma variável quando o jogador passa por cima.',
        'objects.desc.chest': 'Baú que guarda um item para o jogador coletar.',
        'objects.desc.logicGateNot': 'Porta lógica que inverte o estado da variável de entrada.',
        'objects.desc.logicGateAnd': 'Ativa a saída somente quando ambas as entradas estão ON.',
        'objects.desc.logicGateOr': 'Ativa a saída quando pelo menos uma entrada está ON.',
        'objects.desc.logicGateNand': 'Desativa a saída somente quando ambas as entradas estão ON.',
        'objects.desc.logicGateNor': 'Ativa a saída somente quando ambas as entradas estão OFF.',
        'objects.desc.logicLed': 'Indicador visual que acende quando uma variável está ON.',
        'objects.desc.pushBox': 'Caixa que o jogador pode empurrar para acionar placas de pressão.',
        'objects.status.armorEquipped': 'Armadura equipada',
        'objects.status.bootsEquipped': 'Botas equipadas',
        'objects.status.chestOpened': 'Baú aberto',
        'objects.chest.containsLabel': 'Contém:',
        'objects.chest.noItem': '(vazio)',
        'objects.chest.randomItem': 'Item aleatório',
        'objects.logic.inputLabel': 'Entrada:',
        'objects.logic.inputALabel': 'Entrada A:',
        'objects.logic.inputBLabel': 'Entrada B:',
        'objects.logic.outputLabel': 'Saída:',
        'objects.logic.variableLabel': 'Variável:',
        'objects.logic.visibleInGame': 'Visível no jogo',
        'objects.item.pickup': 'Você pegou um item.',
        'objects.key.pickup.single': 'Você pegou uma chave.',
        'objects.key.pickup.count': 'Você pegou uma chave. Agora você tem {value}.',
        'objects.potion.used': 'Você usou uma poção de vida.',
        'objects.xpScroll.read': 'Você leu um pergaminho de XP e ganhou {value} de experiência.',
        'objects.xpScroll.levelUp': 'Nível +{value}!',
        'objects.switch.onMessage': 'Alavanca ligada.',
        'objects.switch.offMessage': 'Alavanca desligada.',
        'objects.sword.pickup.single': 'Você pegou uma {name}! Ela bloqueia 1 de dano no próximo ataque inimigo.',
        'objects.sword.pickup.multi': 'Você pegou uma {name}! Ela bloqueia {value} de dano somando os próximos ataques inimigos.',
        'combat.block.full': 'Ataque bloqueado!',
        'combat.block.partial': 'Bloqueado -{value}',
        'combat.stealthKill': 'Abate furtivo!',
        'combat.stealthMiss': 'Errou o ataque furtivo!',
        'combat.backstab': 'Ataque pelas costas!',
        'combat.tooSoon': 'Muito rápido!',
        'combat.fled': 'Fugiu!',
        'combat.cooldown': 'Invulneravel por um instante!',
        'combat.killedBy': 'Morto por {enemy}',
        'player.levelUp': 'Level Up!',
        'player.levelUp.value': 'Level Up! Nível {value}',
        'skills.levelUpTitle': 'Escolha uma skill',
        'skills.levelUpHint': 'Use 1/2 ou ↑ ↓',
        'skills.pendingLabel': '+{value} escolha(s) na fila',
        'skills.allUnlocked': 'Todas as habilidades já foram aprendidas.',
        'skills.pickupMessage': 'Você aprendeu {name}!',
        'skills.edit.editName': 'Editar nome',
        'skills.edit.editDescription': 'Editar descrição',
        'skills.edit.confirm': 'Confirmar',
        'skills.edit.cancel': 'Cancelar',
        'skills.edit.reset': 'Redefinir para o padrão',
        'skills.edit.nameInput': 'Nome da skill',
        'skills.edit.descriptionInput': 'Descrição da skill',
        'skills.edit.modalTitle': 'Editar Skill',
        'skills.edit.iconLabel': 'Ícone',
        'skills.edit.nameLabel': 'Nome',
        'skills.edit.descLabel': 'Descrição',
        'skills.edit.restoreDefaults': 'Restaurar padrão',
        'skills.edit.save': 'Salvar',
        'skills.edit.openModal': 'Editar skill',
        'skills.edit.iconAriaLabel': 'Ícone da skill',
        'skills.edit.nameAriaLabel': 'Nome da skill',
        'skills.edit.descAriaLabel': 'Descrição da skill',
        'skills.keylessDoors.name': 'Ladinagem',
        'skills.keylessDoors.desc': 'Abre portas trancadas sem gastar chaves.',
        'skills.charisma.name': 'Persuasão',
        'skills.charisma.desc': 'Libera diálogos alternativos com NPCs.',
        'skills.necromancer.name': 'Segunda Chance',
        'skills.necromancer.desc': 'Renasce automaticamente uma vez após a morte.',
        'skills.necromancer.revive': 'Você voltou da morte!',
        'skills.necromancer.revivePrompt': 'Voltar à vida',
        'gameOver.retryVictory': 'Jogar de novo?',
        'gameOver.retryDefeat': 'Tentar novamente?',
        'skills.stealth.name': 'Emboscada',
        'skills.stealth.desc': 'Sempre ataca primeiro contra inimigos fracos.',
        'skills.waterWalker.name': 'Andar sobre Água',
        'skills.waterWalker.desc': 'Anda sobre água.',
        'skills.lavaWalker.name': 'Resistência ao Fogo',
        'skills.lavaWalker.desc': 'Atravessa lava sem sofrer dano.',
        'skills.potionMaster.name': 'Herbalismo',
        'skills.potionMaster.desc': 'Poções restauram todo o HP.',
        'skills.xpBoost.name': 'Estudioso',
        'skills.xpBoost.desc': '+50% de XP ganho.',
        'skills.ironBody.name': 'Cavaleiro de Aço',
        'skills.ironBody.desc': '-1 em todo dano recebido.',
        'game.clearAllEnemies': 'Matou todos os inimigos! As terras estão purificadas e sua força de vida floresce.',
        'enemy.defaultName': 'Inimigo',
        'world.badge.start': 'Start',
        'world.cell.title': 'Mapa ({col}, {row})',
        'editor.map.title': 'Mapa',
        'editor.mapNav.up': 'Ir para cena acima',
        'editor.mapNav.down': 'Ir para cena abaixo',
        'editor.mapNav.left': 'Ir para cena à esquerda',
        'editor.mapNav.right': 'Ir para cena à direita',
        'editor.mobileNav.label': 'Selecionar seção do editor',
        'editor.mobileNav.tiles': 'Mostrar tiles',
        'editor.mobileNav.world': 'Mostrar mapa do mundo',
        'editor.mobileNav.objects': 'Mostrar objetos',
        'editor.mobileNav.npcs': 'Mostrar NPCs',
        'editor.mobileNav.enemies': 'Mostrar inimigos',
        'editor.mobileNav.project': 'Mostrar projeto',
        'tiles.summaryFallback': 'Tile {id}',
        'buttons.explore': 'Explorar',
        'explore.title': 'Explorar Jogos',
        'explore.closeAria': 'Fechar explorar jogos',
        'explore.empty': 'Nenhum jogo disponível ainda.',
        'explore.loadMore': 'Carregar mais',
        'explore.by': 'por',
        'explore.backToMyGame': '← Voltar para meu jogo',
        'explore.subtitle': '{count} pequenas aventuras da comunidade',
        'explore.itchLink': 'itch.io ↗',
        'explore.itchLinkAria': '{title} no itch.io',
        'metrics.title': 'Game Metrics',
        'metrics.tooltip.npcs': 'Quantidade de NPCs posicionados no mapa.',
        'metrics.tooltip.enemies': 'Quantidade de inimigos posicionados em todos os quartos.',
        'metrics.tooltip.items': 'Quantidade de itens posicionados no mapa (poções, chaves, pergaminhos, etc.).',
        'metrics.tooltip.objects': 'Quantidade de objetos interativos posicionados (alavancas, portas, espadas, etc.), excluindo finais de jogo.',
        'metrics.tooltip.endings': 'Quantidade de finais possíveis do jogo — cada objeto "Final do jogo" colocado no mapa conta como um final.',
        'metrics.tooltip.roomExits': 'Quantidade de teleportes entre quartos colocados no mapa. Mostram como os quartos estão conectados.',
        'metrics.tooltip.conditionalDialogs': 'Quantidade de NPCs com um diálogo alternativo configurado — ativado quando uma variável está ativa.',
        'metrics.tooltip.variablesInUse': 'Quantidade de variáveis únicas efetivamente usadas no jogo — referenciadas por NPCs, inimigos ou objetos como condição ou recompensa.',
        'metrics.tooltip.roomsWithTiles': 'Quantidade de quartos que têm ao menos um tile diferente do padrão pintado por você.',
        'metrics.tooltip.paintedTiles': 'Quantidade de tiles modificados em relação ao padrão — inclui tiles de overlay e tiles de chão alterados.',
        'metrics.tooltip.dialogWords': 'Total de palavras escritas nos diálogos dos NPCs, incluindo diálogos alternativos.',
        'metrics.tooltip.customSprites': 'Quantidade de sprites personalizados desenhados por você no editor de pixel art.',
        'metrics.tooltip.walls': 'Quantidade de blocos de colisão pintados por você. Define os caminhos e obstáculos do mapa.'
    },
    'en-US': {
        'intro.byline': 'by {author}',
        'intro.startAdventure': 'Start adventure',
        'tabs.game': 'Game',
        'tabs.editor': 'Editor',
        'sections.tiles': 'Tiles',
        'sections.world': 'World',
        'sections.objects': 'Objects',
        'sections.npcs': 'NPCs',
        'sections.enemies': 'Enemies',
        'sections.project': 'Project',
        'buttons.reset': 'Reset',
        'buttons.newGame': 'New Game',
        'buttons.remove': 'Remove',
        'buttons.move': 'Move',
        'buttons.server': 'Server',
        'server.modal.title': 'Server Status',
        'server.modal.status': 'Status',
        'server.modal.ping': 'Ping',
        'server.modal.players': 'Players',
        'server.modal.room': 'Room',
        'server.modal.role': 'Role',
        'server.modal.disconnected': 'Disconnected',
        'server.modal.connected': 'Connected',
        'server.modal.connecting': 'Connecting...',
        'server.modal.host': 'Host',
        'server.modal.guest': 'Guest',
        'server.modal.spectator': 'Spectator',
        'server.modal.noSession': 'No active session',
        'server.modal.close': 'Close',
        'server.modal.kick': 'Kick',
        'server.full.title': 'Server full',
        'server.full.message': 'This room already has 2 players. Try another room.',
        'server.kicked.title': 'You were kicked',
        'server.kicked.message': 'The host removed you from the room.',
        'server.kicked.button': 'Back to start',
        'aria.reset': 'Restart the current run',
        'aria.newGame': 'Spin up a fresh project in a new tab',
        'touchControls.show': 'Show controls',
        'touchControls.hide': 'Hide controls',
        'touchControls.upLabel': 'Move up',
        'touchControls.downLabel': 'Move down',
        'touchControls.leftLabel': 'Move left',
        'touchControls.rightLabel': 'Move right',
        'doors.variableLocked': 'This door does not open with a key.',
        'doors.openedRemaining': 'You used a key to open the door. Remaining: {value}.',
        'doors.opened': 'You used a key to open the door.',
        'doors.locked': 'Door locked. You need a key.',
        'doors.unlockedSkill': 'Your skill opens the door without a key.',
        'log.engineReady': 'Tiny RPG Studio engine initialized successfully.',
        'npc.dialog.defaultLabel': 'Default dialogue:',
        'npc.dialog.placeholder': 'Type the NPC dialogue...',
        'npc.reward.defaultLabel': 'Enable variable:',
        'npc.toggle.create': 'Create alternate dialogue',
        'npc.toggle.hide': 'Hide alternate dialogue',
        'npc.conditional.variableLabel': 'Condition (variable):',
        'npc.conditional.textLabel': 'Alternate text:',
        'npc.conditional.placeholder': 'Message displayed when the variable is ON.',
        'npc.conditional.rewardLabel': 'Enable variable (conditional):',
        'npc.delete': 'Remove NPC',
        'npc.defaultName': 'NPC',
        'npc.variant.label': 'NPC appearance',
        'npc.variant.human': 'Human',
        'npc.variant.elf': 'Elf',
        'npc.variant.dwarf': 'Dwarf',
        'npc.variant.fixed': 'Extras',
        'npcs.names.oldMage': 'Old Mage',
        'npcs.names.oldMage.human': 'Old Mage',
        'npcs.names.oldMage.elf': 'Old Mage',
        'npcs.names.oldMage.dwarf': 'Old Mage',
        'npcs.names.villagerMan': 'Common man',
        'npcs.names.villagerMan.human': 'Common man',
        'npcs.names.villagerMan.elf': 'Common man',
        'npcs.names.villagerMan.dwarf': 'Common man',
        'npcs.names.villagerWoman': 'Common woman',
        'npcs.names.villagerWoman.human': 'Common woman',
        'npcs.names.villagerWoman.elf': 'Common woman',
        'npcs.names.villagerWoman.dwarf': 'Common woman',
        'npcs.names.child': 'Curious child',
        'npcs.names.child.human': 'Curious child',
        'npcs.names.child.elf': 'Curious child',
        'npcs.names.child.dwarf': 'Curious child',
        'npcs.names.thoughtBubble': 'Balloon',
        'npcs.names.woodenSign': 'Wooden sign',
        'npcs.names.king': 'King',
        'npcs.names.king.human': 'King',
        'npcs.names.king.elf': 'King',
        'npcs.names.king.dwarf': 'King',
        'npcs.names.knight': 'Knight',
        'npcs.names.knight.human': 'Knight',
        'npcs.names.knight.elf': 'Knight',
        'npcs.names.knight.dwarf': 'Knight',
        'npcs.names.thief': 'Thief',
        'npcs.names.thief.human': 'Thief',
        'npcs.names.thief.elf': 'Thief',
        'npcs.names.thief.dwarf': 'Thief',
        'npcs.names.blacksmith': 'Blacksmith',
        'npcs.names.blacksmith.human': 'Blacksmith',
        'npcs.names.blacksmith.elf': 'Blacksmith',
        'npcs.names.blacksmith.dwarf': 'Blacksmith',
        'npcs.dialog.oldMage': 'I guard old secrets.',
        'npcs.dialog.oldMage.human': 'I guard old secrets.',
        'npcs.dialog.oldMage.elf': 'Trees whisper stories to careful ears.',
        'npcs.dialog.oldMage.dwarf': 'Legends echo through the deep caverns.',
        'npcs.dialog.villagerMan': 'Good morning! Can I help?',
        'npcs.dialog.villagerMan.human': 'Good morning! Can I help?',
        'npcs.dialog.villagerMan.elf': 'May the forest guide your steps.',
        'npcs.dialog.villagerMan.dwarf': 'My hands know hammers and pickaxes.',
        'npcs.dialog.villagerWoman': 'What a lovely day to explore.',
        'npcs.dialog.villagerWoman.human': 'What a lovely day to explore.',
        'npcs.dialog.villagerWoman.elf': 'Flowers bloom with good intentions.',
        'npcs.dialog.villagerWoman.dwarf': 'The sound of the forge calms my heart.',
        'npcs.dialog.child': 'Let\'s play adventure!',
        'npcs.dialog.child.human': 'Let\'s play adventure!',
        'npcs.dialog.child.elf': 'Want to race through the woods with me?',
        'npcs.dialog.child.dwarf': 'Let\'s dig a secret tunnel!',
        'npcs.dialog.thoughtBubble': ' ... ',
        'npcs.dialog.woodenSign': 'Beware of the dangers ahead.',
        'npcs.dialog.king': 'Defend our kingdom!',
        'npcs.dialog.king.human': 'Defend our kingdom!',
        'npcs.dialog.king.elf': 'Honor nature above all.',
        'npcs.dialog.king.dwarf': 'Guard the mines with steel and honor.',
        'npcs.dialog.knight': 'I am ready to fight.',
        'npcs.dialog.knight.human': 'I am ready to fight.',
        'npcs.dialog.knight.elf': 'I fight to keep the green alive.',
        'npcs.dialog.knight.dwarf': 'My armor thunders like a war drum.',
        'npcs.dialog.thief': 'No one catches me in the act.',
        'npcs.dialog.thief.human': 'No one catches me in the act.',
        'npcs.dialog.thief.elf': 'I am a shadow between leaves and branches.',
        'npcs.dialog.thief.dwarf': 'Among stone and gold, no one sees me coming.',
        'npcs.dialog.blacksmith': 'My forges are blazing hot.',
        'npcs.dialog.blacksmith.human': 'My forges are blazing hot.',
        'npcs.dialog.blacksmith.elf': 'I forge with living wood and light steel.',
        'npcs.dialog.blacksmith.dwarf': 'Steel and stone; that is how you build.',
        'npc.status.available': 'Available',
        'npc.status.position': 'Map ({col}, {row}) - ({x}, {y})',
        'project.group.development': 'Development',
        'project.group.testing': 'Testing',
        'project.group.appearance': 'Visuals',
        'project.group.online': 'Online',
        'project.online.warning': 'Online mode is still in development. It is not complete and may contain bugs.',
        'project.online.enabled': 'Online Mode',
        'project.online.p2Spawn': 'P2 starts at:',
        'project.online.spawnUnset': 'not set',
        'project.online.generateLink': 'Generate Online Link',
        'project.hideHud': 'Hide HUD',
        'project.disablePixelFont': 'Disable pixel art font',
        'project.showVariableLinks': 'Show variable links in editor',
        'project.disableSkills': 'Disable skills',
        'project.group.info': 'Information',
        'project.group.export': 'Share',
        'project.titleLabel': 'Game name',
        'project.titlePlaceholder': 'Eg: Legends of the Vale',
        'project.authorLabel': 'Author',
        'project.authorPlaceholder': 'Your name or studio',
        'project.languageLabel': 'Language',
        'project.generateUrl': 'Generate share URL',
        'project.shareUrlLabel': 'Game URL',
        'project.importHTML': 'Import Project',
        'project.generateHTML': 'Export Project',
        'pixelArtEditor.title': 'Pixel Art Editor',
        'pixelArtEditor.closeAria': 'Close pixel art editor',
        'pixelArtEditor.paint': 'Paint',
        'pixelArtEditor.erase': 'Erase',
        'pixelArtEditor.reset': 'Restore default',
        'pixelArtEditor.save': 'Save',
        'pixelArtEditor.copyCode': 'Copy code',
        'pixelArtEditor.copyCodeDone': 'Copied!',
        'pixelArtEditor.frameLabel': 'Frame {index}',
        'pixelArtEditor.paletteColor': 'Color {index}',
        'pixelArtEditor.paletteTransparent': 'Transparent',
        'project.variables.title': 'Game variables',
        'project.variables.usage': '{used}/{total} used',
        'project.variables.used': 'In use',
        'project.variables.unused': 'Not used',
        'project.variables.toggle.show': 'Show variables',
        'project.variables.toggle.hide': 'Hide variables',
        'project.skills.title': 'Game skills',
        'project.skills.toggle.show': 'Show skills',
        'project.skills.toggle.hide': 'Hide skills',
        'project.skills.resetOrder': 'Restore default order',
        'project.skills.disabled': 'Skill system disabled',
        'project.skills.level': 'Level {value}',
        'project.test.title': 'Test helpers',
        'project.test.toggle.show': 'Show',
        'project.test.toggle.hide': 'Hide',
        'project.test.hint': 'Testing only: these options are not included in the share URL.',
        'project.test.startLevel': 'Start at level',
        'project.test.levelOption': 'Level {value}',
        'project.test.skills': 'Enable skills for testing',
        'project.test.skillsDisabled': 'Skills are disabled for this game.',
        'project.test.godMode': 'God mode (immortal)',
        'project.test.debugVision': 'Debug: Enemy vision',
        'project.shareHint': 'Generate a URL and share it with friends!',
        'project.paletteDescription': 'Click on a color to customize',
        'project.palettePreset': 'Preset palette',
        'project.palettePresetCustom': 'Custom',
        'project.paletteReset': 'Reset to Default',
        'project.colorPickerTitle': 'Choose Color',
        'project.colorCurrent': 'Current',
        'project.colorNew': 'New',
        'project.colorCancel': 'Cancel',
        'project.colorConfirm': 'Confirm',
        'language.option.ptBR': 'Portuguese (Brazil)',
        'language.option.enUS': 'English (US)',
        'history.undo': 'Undo',
        'history.redo': 'Redo',
        'alerts.npc.full': 'All NPCs are already on the map.',
        'alerts.npc.createError': 'Could not create this NPC.',
        'alerts.npc.selectFirst': 'Select an NPC before placing.',
        'alerts.npc.placeError': 'Could not place the NPC.',
        'alerts.share.unavailable': 'Share feature is not available.',
        'alerts.share.copied': 'Game URL copied to your clipboard!',
        'alerts.share.copyPrompt': 'Copy your game URL:',
        'alerts.share.generateError': 'Unable to generate the game URL.',
        'alerts.share.loadError': 'Unable to load the file.',
        'enemies.damageInfo': ' - Damage: {value}',
        'enemies.variableLabel': 'Variable:',
        'enemies.xpBarLabel': 'Enemies placed',
        'enemies.xpBarValue': '{current} / {total} enemies',
        'enemies.limitReached': 'Max enemies reached',
        'enemies.names.giantRat': 'Giant Rat',
        'enemies.names.bandit': 'Bandit',
        'enemies.names.darkKnight': 'Dark Knight',
        'enemies.names.necromancer': 'Necromancer',
        'enemies.names.dragon': 'Dragon',
        'enemies.names.skeleton': 'Skeleton',
        'enemies.names.fallenKing': 'Fallen King',
        'enemies.names.ancientDemon': 'Ancient Demon',
        'enemies.defeat.dragon': 'Dragon Seal activated!',
        'enemies.defeat.fallenKing': 'Royal Seal awakened!',
        'enemies.defeat.ancientDemon': 'Demonic Seal is active!',
        'variables.none': 'None',
        'variables.skill.bard': 'Skill: Bard (alternate lines)',
        'objects.info.available': 'Available (1 per scene)',
        'objects.info.placed': 'Already on the map (1 per scene)',
        'objects.info.available.global': 'Available (1 per world)',
        'objects.info.placed.global': 'Already on the map (1 per world)',
        'objects.info.count': 'On map: {count}/{max} per scene',
        'objects.category.all': 'All',
        'objects.category.markers': 'Markers',
        'objects.category.equipment': 'Equipment',
        'objects.category.consumables': 'Consumables',
        'objects.category.obstacles': 'Obstacles',
        'objects.category.triggers': 'Triggers',
        'objects.category.logic': 'Logic',
        'variables.names.var1': 'Black',
        'variables.names.var2': 'Dark Blue',
        'variables.names.var3': 'Purple',
        'variables.names.var4': 'Green',
        'variables.names.var5': 'Brown',
        'variables.names.var6': 'Gray',
        'variables.names.var7': 'Light Blue',
        'variables.names.var8': 'Hot Pink',
        'variables.names.var9': 'Yellow',
        'variables.names.var10': 'Light Grey',
        'variables.names.var11': 'White',
        'variables.names.var12': 'Red',
        'variables.names.var13': 'Orange',
        'variables.names.var14': 'Light Green',
        'variables.names.var15': 'Indigo',
        'variables.names.var16': 'Peach',
        'objects.switch.variableLabel': 'Linked variable:',
        'objects.switch.stateLabel': 'Current state: {state}',
        'objects.state.on': 'ON',
        'objects.state.off': 'OFF',
        'objects.status.doorOpened': 'Door opened',
        'objects.status.keyCollected': 'Key collected',
        'objects.status.potionCollected': 'Potion collected',
        'objects.status.scrollUsed': 'Scroll used',
        'objects.status.swordBroken': 'Sword broken',
        'objects.status.gameEnd': 'End of game',
        'objects.end.textLabel': 'Final message:',
        'objects.end.placeholder': 'Type the message shown before "The End"...',
        'objects.end.hint': 'Max {max} characters.',
        'objects.status.startMarker': 'Start marker',
        'objects.label.door': 'Door',
        'objects.label.doorVariable': 'Magic door',
        'objects.label.playerStart': 'Player start',
        'objects.label.playerStart1': 'Player 1 start',
        'objects.label.playerStart2': 'Player 2 start',
        'objects.label.playerEnd': 'Game end',
        'objects.label.switch': 'Switch',
        'objects.label.key': 'Key',
        'objects.label.lifePotion': 'Health potion',
        'objects.label.sword': 'Steel sword',
        'objects.label.swordBronze': 'Bronze sword',
        'objects.label.swordWood': 'Wooden sword',
        'objects.label.xpScroll': 'XP scroll',
        'objects.label.logicGateNot': 'NOT gate',
        'objects.label.logicGateAnd': 'AND gate',
        'objects.label.logicGateOr': 'OR gate',
        'objects.label.logicGateNand': 'NAND gate',
        'objects.label.logicGateNor': 'NOR gate',
        'objects.label.logicLed': 'LED',
        'objects.label.armor': 'Armor',
        'objects.label.boots': 'Boots',
        'objects.label.trap': 'Trap',
        'objects.label.pressurePlate': 'Pressure Plate',
        'objects.label.pushBox': 'Box',
        'objects.label.chest': 'Chest',
        'objects.desc.playerStart': 'Defines the player\'s entry point in the scene.',
        'objects.desc.playerEnd': 'When touched, shows a message and ends the game.',
        'objects.desc.switch': 'Player interacts to toggle a variable on or off.',
        'objects.desc.door': 'Blocks passage; opens only if the player carries a key.',
        'objects.desc.doorVariable': 'Opens or closes automatically based on a variable\'s state.',
        'objects.desc.key': 'Collectible item that unlocks a locked Door.',
        'objects.desc.lifePotion': 'Collectible item that restores health points when used.',
        'objects.desc.xpScroll': 'Collectible item that grants experience when read.',
        'objects.desc.sword': 'Collectible steel sword that blocks damage from enemy attacks.',
        'objects.desc.swordBronze': 'Collectible bronze sword that blocks damage from enemy attacks.',
        'objects.desc.swordWood': 'Collectible wooden sword that blocks damage from enemy attacks.',
        'objects.desc.armor': 'Collectible armor that permanently reduces damage taken.',
        'objects.desc.boots': 'Collectible boots that increase the player\'s movement speed.',
        'objects.desc.trap': 'Deals damage when the player steps on it; activated by a variable.',
        'objects.desc.pressurePlate': 'Activates a variable when the player steps on it.',
        'objects.desc.chest': 'Chest that holds an item for the player to collect.',
        'objects.desc.logicGateNot': 'Logic gate that inverts the input variable\'s state.',
        'objects.desc.logicGateAnd': 'Activates the output only when both inputs are ON.',
        'objects.desc.logicGateOr': 'Activates the output when at least one input is ON.',
        'objects.desc.logicGateNand': 'Deactivates the output only when both inputs are ON.',
        'objects.desc.logicGateNor': 'Activates the output only when both inputs are OFF.',
        'objects.desc.logicLed': 'Visual indicator that lights up when a variable is ON.',
        'objects.desc.pushBox': 'Box the player can push to trigger pressure plates.',
        'objects.status.armorEquipped': 'Armor equipped',
        'objects.status.bootsEquipped': 'Boots equipped',
        'objects.status.chestOpened': 'Chest opened',
        'objects.chest.containsLabel': 'Contains:',
        'objects.chest.noItem': '(empty)',
        'objects.chest.randomItem': 'Random item',
        'objects.logic.inputLabel': 'Input:',
        'objects.logic.inputALabel': 'Input A:',
        'objects.logic.inputBLabel': 'Input B:',
        'objects.logic.outputLabel': 'Output:',
        'objects.logic.variableLabel': 'Variable:',
        'objects.logic.visibleInGame': 'Visible in game',
        'objects.item.pickup': 'You picked up an item.',
        'objects.key.pickup.single': 'You picked up a key.',
        'objects.key.pickup.count': 'You picked up a key. You now have {value}.',
        'objects.potion.used': 'You used a health potion.',
        'objects.xpScroll.read': 'You read an XP scroll and gained {value} experience.',
        'objects.xpScroll.levelUp': 'Level +{value}!',
        'objects.switch.onMessage': 'Switch turned on.',
        'objects.switch.offMessage': 'Switch turned off.',
        'objects.sword.pickup.single': 'You picked up a {name}! It blocks 1 damage from the next enemy attack.',
        'objects.sword.pickup.multi': 'You picked up a {name}! It blocks {value} damage across upcoming enemy attacks.',
        'combat.block.full': 'Attack blocked!',
        'combat.block.partial': 'Blocked -{value}',
        'combat.stealthKill': 'Stealth kill!',
        'combat.stealthMiss': 'Stealth strike missed!',
        'combat.backstab': 'Backstab!',
        'combat.tooSoon': 'Too fast!',
        'combat.fled': 'Fled!',
        'combat.cooldown': 'Invulnerable for a moment!',
        'combat.killedBy': 'Killed by {enemy}',
        'player.levelUp': 'Level Up!',
        'player.levelUp.value': 'Level Up! Level {value}',
        'skills.levelUpTitle': 'Pick a skill',
        'skills.levelUpHint': 'Use 1/2 or ↑ ↓',
        'skills.pendingLabel': '+{value} pick(s) queued',
        'skills.allUnlocked': 'All skills already unlocked.',
        'skills.pickupMessage': 'You learned {name}!',
        'skills.edit.editName': 'Edit name',
        'skills.edit.editDescription': 'Edit description',
        'skills.edit.confirm': 'Confirm',
        'skills.edit.cancel': 'Cancel',
        'skills.edit.reset': 'Reset to default',
        'skills.edit.nameInput': 'Skill name',
        'skills.edit.descriptionInput': 'Skill description',
        'skills.edit.modalTitle': 'Edit Skill',
        'skills.edit.iconLabel': 'Icon',
        'skills.edit.nameLabel': 'Name',
        'skills.edit.descLabel': 'Description',
        'skills.edit.restoreDefaults': 'Restore defaults',
        'skills.edit.save': 'Save',
        'skills.edit.openModal': 'Edit skill',
        'skills.edit.iconAriaLabel': 'Skill icon',
        'skills.edit.nameAriaLabel': 'Skill name',
        'skills.edit.descAriaLabel': 'Skill description',
        'skills.keylessDoors.name': 'Lockpicking',
        'skills.keylessDoors.desc': 'Locked doors open without spending keys.',
        'skills.charisma.name': 'Persuasion',
        'skills.charisma.desc': 'Unlock alternate NPC dialogues.',
        'skills.necromancer.name': 'Second Life',
        'skills.necromancer.desc': 'Automatically revive once after death.',
        'skills.necromancer.revive': 'You returned from death!',
        'skills.necromancer.revivePrompt': 'Return to life',
        'gameOver.retryVictory': 'Play again?',
        'gameOver.retryDefeat': 'Try again?',
        'skills.stealth.name': 'Ambush',
        'skills.stealth.desc': 'Always strikes first against weak enemies.',
        'skills.waterWalker.name': 'Water Walk',
        'skills.waterWalker.desc': 'Water tiles stop blocking your path.',
        'skills.lavaWalker.name': 'Heat Resistance',
        'skills.lavaWalker.desc': 'Stride over lava without harm.',
        'skills.potionMaster.name': 'Herbalism',
        'skills.potionMaster.desc': 'Health potions restore all HP.',
        'skills.xpBoost.name': 'Scholar',
        'skills.xpBoost.desc': '+50% experience gain.',
        'skills.ironBody.name': 'Iron Knight',
        'skills.ironBody.desc': '-1 to every incoming hit.',
        'game.clearAllEnemies': 'You felled every foe. The land is cleansed and your life force swells.',
        'enemy.defaultName': 'Enemy',
        'world.badge.start': 'Start',
        'world.cell.title': 'Map ({col}, {row})',
        'editor.map.title': 'Map',
        'editor.mapNav.up': 'Go to scene above',
        'editor.mapNav.down': 'Go to scene below',
        'editor.mapNav.left': 'Go to scene on the left',
        'editor.mapNav.right': 'Go to scene on the right',
        'editor.mobileNav.label': 'Select editor section',
        'editor.mobileNav.tiles': 'Show tiles',
        'editor.mobileNav.world': 'Show world map',
        'editor.mobileNav.objects': 'Show objects',
        'editor.mobileNav.npcs': 'Show NPCs',
        'editor.mobileNav.enemies': 'Show enemies',
        'editor.mobileNav.project': 'Show project',
        'tiles.summaryFallback': 'Tile {id}',
        'buttons.explore': 'Explore',
        'explore.title': 'Explore Games',
        'explore.closeAria': 'Close explore games',
        'explore.empty': 'No games available yet.',
        'explore.loadMore': 'Load more',
        'explore.by': 'by',
        'explore.backToMyGame': '← Back to my game',
        'explore.subtitle': '{count} tiny adventures from the community',
        'explore.itchLink': 'itch.io ↗',
        'explore.itchLinkAria': '{title} on itch.io',
        'metrics.title': 'Game Metrics',
        'metrics.tooltip.npcs': 'Number of NPCs currently placed on the map.',
        'metrics.tooltip.enemies': 'Number of enemies placed across all rooms.',
        'metrics.tooltip.items': 'Number of items placed on the map (potions, keys, scrolls, etc.).',
        'metrics.tooltip.objects': 'Number of interactive objects placed (switches, doors, swords, etc.), excluding game endings.',
        'metrics.tooltip.endings': 'Number of possible game endings — each "Game End" object placed on the map counts as one ending.',
        'metrics.tooltip.roomExits': 'Number of teleporters between rooms placed on the map. Shows how rooms are connected.',
        'metrics.tooltip.conditionalDialogs': 'Number of NPCs with a conditional dialog configured — shown when a variable is active.',
        'metrics.tooltip.variablesInUse': 'Number of unique variables actually used in the game — referenced by NPCs, enemies, or objects as a condition or reward.',
        'metrics.tooltip.roomsWithTiles': 'Number of rooms with at least one tile painted by you, different from the default.',
        'metrics.tooltip.paintedTiles': 'Number of tiles changed from the default — includes overlay tiles and modified ground tiles.',
        'metrics.tooltip.dialogWords': 'Total word count across all NPC dialogs, including conditional dialogs.',
        'metrics.tooltip.customSprites': 'Number of custom sprites drawn by you in the pixel art editor.',
        'metrics.tooltip.walls': 'Number of collision blocks painted by you. Defines the paths and obstacles in the map.'
    }
};

type TextResourcesApi = {
    defaultLocale: string;
    locale: string;
    bundles: Record<string, Record<string, string> | undefined>;
    getStrings(locale?: string): Record<string, string>;
    detectBrowserLocale(): string;
    setLocale(locale: string, options?: { silent?: boolean; root?: Document | HTMLElement }): boolean;
    getLocale(): string;
    extend(locale: string, strings?: Record<string, string>): void;
    get(key: string | null | undefined, fallback?: string): string;
    format(
        key: string | null | undefined,
        params?: Record<string, string | number | boolean>,
        fallback?: string
    ): string;
    apply(root?: Document | HTMLElement): void;
};

const TextResources: TextResourcesApi = {
    defaultLocale: 'en-US',
    locale: 'en-US',
    bundles: TEXT_BUNDLES as Record<string, Record<string, string>>,

    getStrings(locale: string = TextResources.locale): Record<string, string> {
        const bundle = this.bundles[locale];
        if (bundle) {
            return bundle;
        }
        return this.bundles[this.defaultLocale] ?? {};
    },

    detectBrowserLocale(): string {
        if (typeof navigator === 'undefined') {
            return this.defaultLocale;
        }
        const languages: readonly string[] = Array.isArray(navigator.languages) && navigator.languages.length
            ? navigator.languages
            : [navigator.language || this.defaultLocale];
        for (const lang of languages) {
            const langStr = String(lang);
            if (this.bundles[langStr]) {
                return langStr;
            }
            const short = String(lang || '').split('-')[0];
            const match = Object.keys(this.bundles).find((locale) => locale.startsWith(short));
            if (match) {
                return match;
            }
        }
        return this.defaultLocale;
    },

    setLocale(locale: string, { silent = false, root }: { silent?: boolean; root?: Document | HTMLElement } = {}): boolean {
        if (!this.bundles[locale]) {
            return false;
        }
        this.locale = locale;
        if (!silent) {
            this.apply(root);
            document.dispatchEvent(new CustomEvent('language-changed', { detail: { locale: this.locale } }));
        }
        return true;
    },

    getLocale(): string {
        return this.locale;
    },

    extend(locale: string, strings: Record<string, string> = {}): void {
        if (!locale || typeof strings !== 'object') return;
        const existing = this.bundles[locale];
        this.bundles[locale] = { ...existing, ...strings };
        if (locale === this.locale) {
            this.apply();
        }
    },

    get(key: string | null | undefined, fallback = ''): string {
        if (!key) return fallback || '';
        const strings = this.getStrings(this.locale) as Record<string, string>;
        if (Object.prototype.hasOwnProperty.call(strings, key)) {
            const value = strings[key];
            return (typeof value === 'string' ? value : fallback) || '';
        }
        if (this.locale !== this.defaultLocale) {
            const defaultStrings = this.getStrings(this.defaultLocale) as Record<string, string>;
            if (Object.prototype.hasOwnProperty.call(defaultStrings, key)) {
                const value = defaultStrings[key];
                return (typeof value === 'string' ? value : fallback) || '';
            }
        }
        return fallback || key || '';
    },

    format(
        key: string | null | undefined,
        params: Record<string, string | number | boolean | null | undefined> = {},
        fallback = ''
    ): string {
        const template = this.get(key, fallback) as string;
        if (!template) return fallback || key || '';
        const result: string = template.replace(/\{(\w+)\}/g, (_: string, token: string) => {
            if (Object.prototype.hasOwnProperty.call(params, token)) {
                const value = params[token];
                return value === undefined || value === null ? '' : String(value);
            }
            return '';
        });
        return result;
    },

    apply(root: Document | HTMLElement = document): void {
        if (typeof root.querySelectorAll !== 'function') return;
        root.querySelectorAll('[data-text-key]').forEach((el) => {
            const key = el.getAttribute('data-text-key');
            const fallbackContent = (el.textContent as string | null | undefined) ?? '';
            const text: string = this.get(key, fallbackContent) as string;
            el.textContent = text;
        });

        root.querySelectorAll('[data-placeholder-key]').forEach((el) => {
            const key = el.getAttribute('data-placeholder-key');
            const text: string = this.get(key, el.getAttribute('placeholder') || '') as string;
            if (text) {
                el.setAttribute('placeholder', text);
            }
        });

        root.querySelectorAll('[data-aria-label-key]').forEach((el) => {
            const key = el.getAttribute('data-aria-label-key');
            const text: string = this.get(key, el.getAttribute('aria-label') || '') as string;
            if (text) {
                el.setAttribute('aria-label', text);
            }
        });

        root.querySelectorAll('[data-title-key]').forEach((el) => {
            const key = el.getAttribute('data-title-key');
            const text: string = this.get(key, el.getAttribute('title') || '') as string;
            if (text) {
                el.setAttribute('title', text);
            }
        });
    }
};

if (typeof document !== 'undefined') {
    document.addEventListener('DOMContentLoaded', () => {
        const detected: string = TextResources.detectBrowserLocale() as string;
        TextResources.setLocale(detected, { silent: true });
        TextResources.apply();
    });
}

export { TextResources };
