
class EditorDomCache {
    root: Document | HTMLElement;
    editorCanvas: HTMLCanvasElement | null;
    mapPosition: HTMLElement | null;
    mapNavButtons: HTMLElement[];
    mobileNavButtons: HTMLElement[];
    mobilePanels: HTMLElement[];
    selectedTilePreview: HTMLElement | null;
    tileSummary: HTMLElement | null;
    tileList: HTMLElement | null;
    npcsList: HTMLElement | null;
    npcText: HTMLTextAreaElement | null;
    npcConditionalText: HTMLTextAreaElement | null;
    npcConditionalVariable: HTMLSelectElement | null;
    npcRewardVariable: HTMLSelectElement | null;
    npcConditionalRewardVariable: HTMLSelectElement | null;
    btnToggleNpcConditional: HTMLElement | null;
    npcConditionalSection: HTMLElement | null;
    npcVariantButtons: HTMLElement[];
    objectCategoryButtons: HTMLElement[];
    worldGrid: HTMLElement | null;
    worldMetrics: HTMLElement | null;
    titleInput: HTMLInputElement | null;
    authorInput: HTMLInputElement | null;
    fileInput: HTMLInputElement | null;
    objectTypes: HTMLElement | null;
    objectsList: HTMLElement | null;
    btnNpcDelete: HTMLElement | null;
    npcEditor: HTMLElement | null;
    btnGenerateUrl: HTMLElement | null;
    shareUrlInput: HTMLInputElement | null;
    btnUndo: HTMLElement | null;
    btnRedo: HTMLElement | null;
    enemyTypes: HTMLElement | null;
    projectVariablesContainer: HTMLElement | null;
    projectTabButtons: HTMLElement[];
    projectTabPanels: HTMLElement[];
    projectVariablesToggle: HTMLElement | null;
    projectVariableList: HTMLElement | null;
    projectVariableSummary: HTMLElement | null;
    projectSkillsContainer: HTMLElement | null;
    projectSkillsToggle: HTMLElement | null;
    projectSkillsList: HTMLElement | null;
    projectTestContainer: HTMLElement | null;
    projectTestToggle: HTMLElement | null;
    projectTestPanel: HTMLElement | null;
    projectTestStartLevel: HTMLSelectElement | null;
    projectTestSkillList: HTMLElement | null;
    projectTestGodMode: HTMLInputElement | null;
    projectTestDebugVision: HTMLInputElement | null;
    projectPaletteContainer: HTMLElement | null;
    projectPalettePanel: HTMLElement | null;
    paletteGrid: HTMLElement | null;
    palettePresetSelect: HTMLSelectElement | null;
    paletteResetButton: HTMLButtonElement | null;
    paletteImportButton: HTMLButtonElement | null;
    paletteExportButton: HTMLButtonElement | null;
    spritesImportButton: HTMLButtonElement | null;
    spritesExportButton: HTMLButtonElement | null;
    spritesClearButton: HTMLButtonElement | null;
    projectSkillsResetOrder: HTMLButtonElement | null;
    projectEnableEffects: HTMLInputElement | null;
    customTileEffectOpen: HTMLButtonElement | null = null;
    customTileEffectModal: HTMLElement | null = null;
    projectHideHud: HTMLInputElement | null;
    projectSpriteOutline: HTMLInputElement | null;
    projectSpriteOutlineColor: HTMLSelectElement | null;
    projectDisableSkills: HTMLInputElement | null;
    projectOnlineEnabled: HTMLInputElement | null;
    projectOnlineControls: HTMLElement | null;
    btnStartOnlineServer: HTMLButtonElement | null;
    btnSetP2Spawn: HTMLButtonElement | null;
    onlineP2SpawnLabel: HTMLElement | null;
    onlineServerUrlRow: HTMLElement | null;
    onlineServerUrl: HTMLInputElement | null;
    projectBackgroundMusicUrl: HTMLInputElement | null;
    projectBackgroundMusicVolume: HTMLInputElement | null;
    projectBackgroundMusicVolumeValue: HTMLElement | null;
    projectDisablePixelFont: HTMLInputElement | null;
    projectShowVariableLinks: HTMLInputElement | null;
    colorPickerModal: HTMLElement | null;
    colorPickerInput: HTMLInputElement | null;
    colorPickerConfirm: HTMLButtonElement | null;
    colorPickerCancel: HTMLButtonElement | null;
    colorPreviewCurrent: HTMLElement | null;
    colorPreviewNew: HTMLElement | null;
    colorPickerIndex: HTMLElement | null;
    jsonArea?: HTMLTextAreaElement | null;
    pixelArtEditorModal: HTMLElement | null = null;
    paeCanvas: HTMLCanvasElement | null = null;
    paePalette: HTMLElement | null = null;
    paeSpriteMeta: HTMLElement | null = null;
    paeVariantBar: HTMLElement | null = null;
    paeFrameBar: HTMLElement | null = null;
    paeSave: HTMLButtonElement | null = null;
    paeReset: HTMLButtonElement | null = null;
    paeClose: HTMLButtonElement | null = null;
    paeCopyCode: HTMLButtonElement | null = null;
    paeToolPaint: HTMLButtonElement | null = null;
    paeToolErase: HTMLButtonElement | null = null;
    paeTileEffectRow: HTMLElement | null = null;
    paeTileEffect: HTMLSelectElement | null = null;
    npcEditModal: HTMLElement | null = null;
    repositionIndicator: HTMLElement | null = null;
    objectEditModal: HTMLElement | null = null;
    enemyEditModal: HTMLElement | null = null;
    skillEditModal: HTMLElement | null = null;
    skillEditIconInput: HTMLInputElement | null = null;
    skillEditIconPreview: HTMLElement | null = null;
    skillEditNameInput: HTMLInputElement | null = null;
    skillEditNameCounter: HTMLElement | null = null;
    skillEditDescInput: HTMLTextAreaElement | null = null;
    skillEditDescCounter: HTMLElement | null = null;
    skillEditSaveBtn: HTMLButtonElement | null = null;
    skillEditCancelBtn: HTMLButtonElement | null = null;
    skillEditRestoreBtn: HTMLButtonElement | null = null;

    constructor(root: Document | HTMLElement | null = typeof document !== 'undefined' ? document : null) {
        this.root = root || (null as unknown as Document); // fallback for strict mode if needed, though properties can be null
        if (!root) {
            this.editorCanvas = null;
            this.mapPosition = null;
            this.mapNavButtons = [];
            this.mobileNavButtons = [];
            this.mobilePanels = [];
            this.selectedTilePreview = null;
            this.tileSummary = null;
            this.tileList = null;
            this.npcsList = null;
            this.npcText = null;
            this.npcConditionalText = null;
            this.npcConditionalVariable = null;
            this.npcRewardVariable = null;
            this.npcConditionalRewardVariable = null;
            this.btnToggleNpcConditional = null;
            this.npcConditionalSection = null;
            this.npcVariantButtons = [];
            this.objectCategoryButtons = [];
            this.worldGrid = null;
            this.worldMetrics = null;
            this.titleInput = null;
            this.authorInput = null;
            this.fileInput = null;
            this.objectTypes = null;
            this.objectsList = null;
            this.btnNpcDelete = null;
            this.npcEditor = null;
            this.btnGenerateUrl = null;
            this.shareUrlInput = null;
            this.btnUndo = null;
            this.btnRedo = null;
            this.enemyTypes = null;
            this.projectVariablesContainer = null;
            this.projectTabButtons = [];
            this.projectTabPanels = [];
            this.projectVariablesToggle = null;
            this.projectVariableList = null;
            this.projectVariableSummary = null;
            this.projectSkillsContainer = null;
            this.projectSkillsToggle = null;
            this.projectSkillsList = null;
            this.projectTestContainer = null;
            this.projectTestToggle = null;
            this.projectTestPanel = null;
            this.projectTestStartLevel = null;
            this.projectTestSkillList = null;
            this.projectTestGodMode = null;
            this.projectTestDebugVision = null;
            this.projectPaletteContainer = null;
            this.projectPalettePanel = null;
            this.paletteGrid = null;
            this.palettePresetSelect = null;
            this.paletteResetButton = null;
            this.paletteImportButton = null;
            this.paletteExportButton = null;
            this.spritesImportButton = null;
            this.spritesExportButton = null;
            this.spritesClearButton = null;
            this.projectSkillsResetOrder = null;
            this.projectEnableEffects = null;
            this.projectHideHud = null;
            this.projectSpriteOutline = null;
            this.projectSpriteOutlineColor = null;
            this.projectDisableSkills = null;
            this.projectOnlineEnabled = null;
            this.projectOnlineControls = null;
            this.btnStartOnlineServer = null;
            this.btnSetP2Spawn = null;
            this.onlineP2SpawnLabel = null;
            this.onlineServerUrlRow = null;
            this.onlineServerUrl = null;
            this.projectBackgroundMusicUrl = null;
            this.projectBackgroundMusicVolume = null;
            this.projectBackgroundMusicVolumeValue = null;
            this.projectDisablePixelFont = null;
            this.projectShowVariableLinks = null;
            this.colorPickerModal = null;
            this.colorPickerInput = null;
            this.colorPickerConfirm = null;
            this.colorPickerCancel = null;
            this.colorPreviewCurrent = null;
            this.colorPreviewNew = null;
            this.colorPickerIndex = null;
            this.jsonArea = null;
            this.npcEditModal = null;
            this.repositionIndicator = null;
            this.objectEditModal = null;
            this.enemyEditModal = null;
            this.pixelArtEditorModal = null;
            this.paeCanvas = null;
            this.paePalette = null;
            this.paeSpriteMeta = null;
            this.paeVariantBar = null;
            this.paeFrameBar = null;
            this.paeSave = null;
            this.paeReset = null;
            this.paeClose = null;
            this.paeCopyCode = null;
            this.paeToolPaint = null;
            this.paeToolErase = null;
            this.paeTileEffectRow = null;
            this.paeTileEffect = null;
            return;
        }

        this.editorCanvas = root.querySelector('#editor-canvas') as HTMLCanvasElement | null;
        this.mapPosition = root.querySelector('#editor-map-position') as HTMLElement | null;
        this.mapNavButtons = Array.from(root.querySelectorAll('.map-nav-button'));
        this.mobileNavButtons = Array.from(root.querySelectorAll('.editor-mobile-nav-button'));
        this.mobilePanels = Array.from(root.querySelectorAll('.editor-section[data-mobile-panel]'));
        this.selectedTilePreview = root.querySelector('#selected-tile-preview') as HTMLElement | null;
        this.tileSummary = root.querySelector('#tile-preset-summary') as HTMLElement | null;
        this.tileList = root.querySelector('#tile-list') as HTMLElement | null;
        this.npcsList = root.querySelector('#npcs-list') as HTMLElement | null;
        this.npcText = root.querySelector('#npc-text') as HTMLTextAreaElement | null;
        this.npcConditionalText = root.querySelector('#npc-conditional-text') as HTMLTextAreaElement | null;
        this.npcConditionalVariable = root.querySelector('#npc-conditional-variable') as HTMLSelectElement | null;
        this.npcRewardVariable = root.querySelector('#npc-reward-variable') as HTMLSelectElement | null;
        this.npcConditionalRewardVariable = root.querySelector('#npc-conditional-reward-variable') as HTMLSelectElement | null;
        this.btnToggleNpcConditional = root.querySelector('#btn-toggle-npc-conditional') as HTMLElement | null;
        this.npcConditionalSection = root.querySelector('#npc-conditional-section') as HTMLElement | null;
        this.npcVariantButtons = Array.from(root.querySelectorAll('[data-npc-variant-filter]'));
        this.objectCategoryButtons = Array.from(root.querySelectorAll('[data-object-category-filter]'));
        this.worldGrid = root.querySelector('#world-grid') as HTMLElement | null;
        this.worldMetrics = root.querySelector('#world-metrics') as HTMLElement | null;
        this.titleInput = root.querySelector('#game-title') as HTMLInputElement | null;
        this.authorInput = root.querySelector('#game-author') as HTMLInputElement | null;
        this.fileInput = root.querySelector('#file-input') as HTMLInputElement | null;
        this.objectTypes = root.querySelector('#object-types') as HTMLElement | null;
        this.objectsList = root.querySelector('#objects-list') as HTMLElement | null;
        this.btnNpcDelete = root.querySelector('#npc-delete') as HTMLElement | null;
        this.npcEditor = root.querySelector('.npc-editor') as HTMLElement | null;
        this.btnGenerateUrl = root.querySelector('#btn-generate-url') as HTMLElement | null;
        this.shareUrlInput = root.querySelector('#project-share-url') as HTMLInputElement | null;
        this.btnUndo = root.querySelector('#btn-undo') as HTMLElement | null;
        this.btnRedo = root.querySelector('#btn-redo') as HTMLElement | null;
        this.enemyTypes = root.querySelector('#enemy-types') as HTMLElement | null;
        this.projectVariablesContainer = root.querySelector('#project-variables-container') as HTMLElement | null;
        this.projectTabButtons = Array.from(root.querySelectorAll('[data-project-tab-button]'));
        this.projectTabPanels = Array.from(root.querySelectorAll('[data-project-tab-panel]'));
        this.projectVariablesToggle = root.querySelector('#project-variables-toggle') as HTMLElement | null;
        this.projectVariableList = root.querySelector('#project-variable-usage-list') as HTMLElement | null;
        this.projectVariableSummary = root.querySelector('#project-variable-usage-summary') as HTMLElement | null;
        this.projectSkillsContainer = root.querySelector('#project-skills-container') as HTMLElement | null;
        this.projectSkillsToggle = root.querySelector('#project-skills-toggle') as HTMLElement | null;
        this.projectSkillsList = root.querySelector('#project-skills-list') as HTMLElement | null;
        this.projectTestContainer = root.querySelector('#project-test-container') as HTMLElement | null;
        this.projectTestToggle = root.querySelector('#project-test-toggle') as HTMLElement | null;
        this.projectTestPanel = root.querySelector('#project-test-panel') as HTMLElement | null;
        this.projectTestStartLevel = root.querySelector('#project-test-start-level') as HTMLSelectElement | null;
        this.projectTestSkillList = root.querySelector('#project-test-skill-list') as HTMLElement | null;
        this.projectTestGodMode = root.querySelector('#project-test-god-mode') as HTMLInputElement | null;
        this.projectTestDebugVision = root.querySelector('#project-test-debug-vision') as HTMLInputElement | null;
        this.projectPaletteContainer = root.querySelector('#project-palette-container') as HTMLElement | null;
        this.projectPalettePanel = root.querySelector('#project-palette-panel') as HTMLElement | null;
        this.paletteGrid = root.querySelector('#palette-grid') as HTMLElement | null;
        this.palettePresetSelect = root.querySelector('#palette-preset-select') as HTMLSelectElement | null;
        this.paletteResetButton = root.querySelector('#palette-reset-button') as HTMLButtonElement | null;
        this.paletteImportButton = root.querySelector('#palette-import-button') as HTMLButtonElement | null;
        this.paletteExportButton = root.querySelector('#palette-export-button') as HTMLButtonElement | null;
        this.spritesImportButton = root.querySelector('#sprites-import-button') as HTMLButtonElement | null;
        this.spritesExportButton = root.querySelector('#sprites-export-button') as HTMLButtonElement | null;
        this.spritesClearButton = root.querySelector('#sprites-clear-button') as HTMLButtonElement | null;
        this.projectSkillsResetOrder = root.querySelector('#project-skills-reset-order') as HTMLButtonElement | null;
        this.projectEnableEffects = root.querySelector('#project-enable-effects') as HTMLInputElement | null;
        this.customTileEffectOpen = root.querySelector('#custom-effect-open') as HTMLButtonElement | null;
        this.customTileEffectModal = root.querySelector('#custom-effect-modal') as HTMLElement | null;
        this.projectHideHud = root.querySelector('#project-hide-hud') as HTMLInputElement | null;
        this.projectSpriteOutline = root.querySelector('#project-sprite-outline') as HTMLInputElement | null;
        this.projectSpriteOutlineColor = root.querySelector('#project-sprite-outline-color') as HTMLSelectElement | null;
        this.projectDisableSkills = root.querySelector('#project-disable-skills') as HTMLInputElement | null;
        this.projectOnlineEnabled = root.querySelector('#project-online-enabled') as HTMLInputElement | null;
        this.projectOnlineControls = root.querySelector('#project-online-controls') as HTMLElement | null;
        this.btnStartOnlineServer = root.querySelector('#btn-start-online-server') as HTMLButtonElement | null;
        this.btnSetP2Spawn = root.querySelector('#btn-set-p2-spawn') as HTMLButtonElement | null;
        this.onlineP2SpawnLabel = root.querySelector('#online-p2-spawn-label') as HTMLElement | null;
        this.onlineServerUrlRow = root.querySelector('#online-server-url-row') as HTMLElement | null;
        this.onlineServerUrl = root.querySelector('#online-server-url') as HTMLInputElement | null;
        this.projectBackgroundMusicUrl = root.querySelector('#project-background-music-url') as HTMLInputElement | null;
        this.projectBackgroundMusicVolume = root.querySelector('#project-background-music-volume') as HTMLInputElement | null;
        this.projectBackgroundMusicVolumeValue = root.querySelector('#project-background-music-volume-value') as HTMLElement | null;
        this.projectDisablePixelFont = root.querySelector('#project-disable-pixel-font') as HTMLInputElement | null;
        this.projectShowVariableLinks = root.querySelector('#project-show-variable-links') as HTMLInputElement | null;
        this.colorPickerModal = root.querySelector('#color-picker-modal') as HTMLElement | null;
        this.colorPickerInput = root.querySelector('#color-picker-input') as HTMLInputElement | null;
        this.colorPickerConfirm = root.querySelector('#color-picker-confirm') as HTMLButtonElement | null;
        this.colorPickerCancel = root.querySelector('#color-picker-cancel') as HTMLButtonElement | null;
        this.colorPreviewCurrent = root.querySelector('#color-preview-current .color-preview-swatch') as HTMLElement | null;
        this.colorPreviewNew = root.querySelector('#color-preview-new .color-preview-swatch') as HTMLElement | null;
        this.colorPickerIndex = root.querySelector('#color-picker-index') as HTMLElement | null;
        this.jsonArea = root.querySelector('#json-area') as HTMLTextAreaElement | null;
        this.npcEditModal = root.querySelector('#npc-edit-modal') as HTMLElement | null;
        this.repositionIndicator = root.querySelector('#reposition-indicator') as HTMLElement | null;
        this.objectEditModal = root.querySelector('#object-edit-modal') as HTMLElement | null;
        this.enemyEditModal = root.querySelector('#enemy-edit-modal') as HTMLElement | null;
        this.pixelArtEditorModal = root.querySelector('#pixel-art-editor-modal') as HTMLElement | null;
        this.paeCanvas = root.querySelector('#pae-canvas') as HTMLCanvasElement | null;
        this.paePalette = root.querySelector('#pae-palette') as HTMLElement | null;
        this.paeSpriteMeta = root.querySelector('#pae-sprite-meta') as HTMLElement | null;
        this.paeVariantBar = root.querySelector('#pae-variant-bar') as HTMLElement | null;
        this.paeFrameBar = root.querySelector('#pae-frame-bar') as HTMLElement | null;
        this.paeSave = root.querySelector('#pae-save') as HTMLButtonElement | null;
        this.paeReset = root.querySelector('#pae-reset') as HTMLButtonElement | null;
        this.paeClose = root.querySelector('#pae-close') as HTMLButtonElement | null;
        this.paeCopyCode = root.querySelector('#pae-copy-code') as HTMLButtonElement | null;
        this.paeToolPaint = root.querySelector('#pae-tool-paint') as HTMLButtonElement | null;
        this.paeToolErase = root.querySelector('#pae-tool-erase') as HTMLButtonElement | null;
        this.paeTileEffectRow = root.querySelector('#pae-tile-effect-row') as HTMLElement | null;
        this.paeTileEffect = root.querySelector('#pae-tile-effect') as HTMLSelectElement | null;
        this.skillEditModal = root.querySelector('#skill-edit-modal') as HTMLElement | null;
        this.skillEditIconInput = root.querySelector('#skill-edit-icon') as HTMLInputElement | null;
        this.skillEditIconPreview = root.querySelector('#skill-edit-icon-preview') as HTMLElement | null;
        this.skillEditNameInput = root.querySelector('#skill-edit-name') as HTMLInputElement | null;
        this.skillEditNameCounter = root.querySelector('#skill-edit-name-counter') as HTMLElement | null;
        this.skillEditDescInput = root.querySelector('#skill-edit-desc') as HTMLTextAreaElement | null;
        this.skillEditDescCounter = root.querySelector('#skill-edit-desc-counter') as HTMLElement | null;
        this.skillEditSaveBtn = root.querySelector('#skill-edit-save') as HTMLButtonElement | null;
        this.skillEditCancelBtn = root.querySelector('#skill-edit-cancel') as HTMLButtonElement | null;
        this.skillEditRestoreBtn = root.querySelector('#skill-edit-restore') as HTMLButtonElement | null;
    }
}

export { EditorDomCache };
